apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: libs-omnibus
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: libs-omnibus
    spec:
      hostNetwork: true
      hostname: libs-omnibus
      dnsPolicy: ClusterFirstWithHostNet
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "libs-omnibus"
      containers:
      -  name: libs-omnibus
         image: iawake/libs-omnibus:0.0.0
         env:
          - name: ROS_HOSTNAME
            value: libs-omnibus
          - name: ROS_MASTER_URI
            value: http://ros-master:11311

---
apiVersion: v1
kind: Service
metadata:
  name: libs-omnibus
spec:
  clusterIP: None
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: libs-omnibus
  type: ClusterIP
